backend:
  name: github
  branch: master
  repo: aaltogamers/AG_web
  #base_url: http://localhost:3000
  base_url: https://ag-website-hbgde7hkbwbscse9.northeurope-01.azurewebsites.net
  auth_endpoint: /api/auth
  squash_merges: true
publish_mode: simple
media_folder: public/images
public_folder: /images
local_backend: true
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Partners'
        name: 'partners'
        file: 'src/content/partners.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About'
        name: 'about'
        file: 'src/content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Board Title', name: 'boardTitle', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Safer Space Policy'
        name: 'safespace'
        file: 'src/content/safespace.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Harassment contact people names', name: 'contactPeopleNames', widget: 'list' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Image Showcase'
        name: 'imageshowcase'
        file: 'src/content/imageShowCase.md'
        fields:
          - label: 'Images'
            name: 'images'
            label_singular: 'Images'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
      - label: 'Leaderboard'
        name: 'leaderboard'
        file: 'src/content/leaderboard.md'
        fields:
          - label: 'Leaderboard entries'
            name: 'learderboard_entries'
            label_singular: 'Leaderboard entry'
            widget: 'list'
            allow_add: true
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Discord User ID', name: 'discord_user_id', widget: 'string' }
              - label: 'Point entries'
                name: 'point_entries'
                label_singular: 'Point entry'
                widget: 'list'
                allow_add: true
                summary: '{{fields.points_acquired_on}} - {{fields.points}}'
                fields:
                  - { label: Points, name: points, widget: number, required: true }
                  - {
                      label: Point acquired on,
                      name: points_acquired_on,
                      widget: datetime,
                      format: 'DD.MM.YYYY',
                      date_format: 'DD.MM.YYYY',
                      time_format: false,
                      required: true,
                    }
  - label: 'Partner'
    name: 'partner'
    folder: 'src/content/partners'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Finnish Link', name: 'finnishLink', widget: 'string', required: false }
      - { label: 'English Link', name: 'englishLink', widget: 'string', required: false }
      #- { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - label: 'Event'
    name: 'event'
    folder: 'src/content/events'
    create: true
    identifier_field: name
    sortable_fields: ['time', 'name']
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Time', name: 'time', widget: 'datetime', required: false }
      - label: 'Other times for calendar'
        name: 'otherTimes'
        widget: 'list'
        summary: '{{fields.time}} {{fields.name}}'
        required: false
        add_to_top: true
        collapsed: true
        fields:
          - { label: 'Time', name: 'time', widget: 'datetime' }
          - { label: Name, name: name, widget: string, required: false }

      - {
          label: 'Duration (hours)',
          name: 'durationHours',
          widget: 'number',
          value_type: 'int',
          min: 0,
          default: 8,
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - {
          label: 'Visible on calendar',
          name: 'visibleOnCalendar',
          widget: 'boolean',
          default: true,
        }
      - {
          label: 'Visible on events page',
          name: 'visibleOnEventsPage',
          widget: 'boolean',
          default: true,
        }
      - { label: 'Location', name: 'location', widget: 'string', required: false }
      - { label: 'Recurring', name: 'isRecurring', widget: 'boolean', 'required': false }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'TLDR', name: 'tldr', widget: 'markdown', default: "
            ### WHEN?\n
            XX-XX on XX\n\n
            ### WHERE?\n
            XX\n\n
            ### WHY?\n
            To Win XX, to have fun with friends, etc.\n\n
            ### SIGN-UP\n
            LINK\n
            Open from XX to XX
            " }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Landing info'
    name: 'landinginfo'
    folder: 'src/content/landinginfos'
    create: true
    identifier_field: Title
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Board member'
    name: 'boardmember'
    folder: 'src/content/boardmembers'
    create: true
    identifier_field: Name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Status', name: 'status', widget: 'string' }
      - { label: 'Game', name: 'game', widget: 'string' }
      - {
          label: 'Order number',
          name: 'orderNumber',
          widget: 'number',
          value_type: 'int',
          min: 1,
          max: 20,
          hint: 'The order in which the board members are displayed. Smallest first.',
        }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
  - label: 'Album'
    name: 'album'
    folder: 'src/content/albums'
    create: true
    identifier_field: name
    fields:
      - {
          label: 'Name',
          name: 'name',
          widget: 'string',
          hint: 'WARNING: When creating an album, you need to manually make a folder in /public/images/albums/ and store the images there. ',
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - {
          label: 'Order number',
          name: 'orderNumber',
          widget: 'number',
          value_type: 'int',
          min: 1,
          hint: 'The order in which the albums are displayed. Smallest first.',
        }
      - {
          label: 'Event',
          name: 'event',
          widget: 'relation',
          collection: 'event',
          value_field: 'name',
          search_fields: ['name'],
          required: false,
        }

  - label: 'Redirect Links'
    name: 'links'
    files:
      - label: 'Redirect links'
        name: 'links'
        file: 'public/redirects.md'
        fields:
          - label: 'Redirect links'
            label_singular: 'Redirect link'
            name: 'redirects'
            widget: 'list'
            allow_add: true
            fields:
              - { label: 'Name', name: 'name', widget: 'string', placeholder: 'AG Twitch' }
              - {
                  label: 'Path',
                  name: 'slug',
                  widget: 'string',
                  hint: 'The end of the url on the AG website, e.g. aaltogamers.fi/link/*this*',
                }
              - { label: 'URL', name: 'url', widget: 'string' }
